// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ChangePassword struct {
	Oldpassword string `json:"oldpassword"`
	Newpassword string `json:"newpassword"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID         int       `json:"id"`
	Username   string    `json:"username"`
	Role       string    `json:"role"`
	CreateTime time.Time `json:"createTime"`
	UpdateTime time.Time `json:"updateTime"`
}
