// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ChangePassword struct {
	Oldpassword string `json:"oldpassword"`
	Newpassword string `json:"newpassword"`
}

type DeviceIP struct {
	// Static or DHCP.
	Type string `json:"type"`
	// IPv4 with CIDR prefix to set or empty for DHCP.
	IP string `json:"ip"`
	// Optional gateway IPv4 in the same subnet. Empty clears it; must be empty for DHCP.
	Gateway string `json:"gateway"`
	// Up to eight IPv4 DNS servers. Empty clears them; must be empty for DHCP.
	DNS []string `json:"dns"`
}

type DeviceStatus struct {
	// Hostname of the device
	Hostname string `json:"hostname"`
	// Active NetworkManager IPv4 profile method: static, DHCP, link-local, shared, disabled, or unknown.
	LanIPType string `json:"lanIPType"`
	// One eth0 IPv4 address with CIDR prefix; prefers non-link-local, then lexical order. Empty if absent.
	LanIP string `json:"lanIP"`
	// NetworkManager's active eth0 IPv4 gateway; empty if absent.
	Gateway string `json:"gateway"`
	// IPv4 and IPv6 DNS servers reported by NetworkManager for eth0, not the system resolver stub.
	DNS []string `json:"dns"`
	// Active NetworkManager IPv6 profile method; auto means SLAAC and/or DHCPv6, unknown if no active profile.
	LanIPv6Type string `json:"lanIPv6Type"`
	// One eth0 IPv6 address with CIDR prefix; prefers non-link-local, then lexical order. Empty if absent.
	LanIPv6 string `json:"lanIPv6"`
	// NetworkManager's active eth0 IPv6 gateway; empty if absent.
	Gateway6 string `json:"gateway6"`
	// MAC address of eth0.
	EthAddr string `json:"ethAddr"`
	// CPU utilization across all cores over 200 ms, rounded to 0–100 percent.
	Cpuload int32 `json:"cpuload"`
	// RAM usage based on MemTotal minus MemAvailable, rounded to 0–100 percent.
	Memory int32 `json:"memory"`
	// System boot time, not the portal process start time.
	LastRestart time.Time `json:"lastRestart"`
	// System uptime in whole seconds.
	Uptime int `json:"uptime"`
	// Currently always healthy; system-health checks are not implemented yet.
	Health string `json:"health"`
}

type Mutation struct {
}

type Query struct {
}

type Tailnet struct {
	Name            string `json:"name"`
	MagicDNSSuffix  string `json:"magicDNSSuffix"`
	MagicDNSEnabled bool   `json:"magicDNSEnabled"`
}

type TailscaleClient struct {
	ID              int       `json:"id"`
	ClientID        string    `json:"clientId"`
	HasClientSecret bool      `json:"hasClientSecret"`
	CreateTime      time.Time `json:"createTime"`
	UpdateTime      time.Time `json:"updateTime"`
}

type TailscaleClientVersion struct {
	RunningLatest        bool   `json:"runningLatest"`
	LatestVersion        string `json:"latestVersion"`
	UrgentSecurityUpdate bool   `json:"urgentSecurityUpdate"`
	Notify               bool   `json:"notify"`
	NotifyURL            string `json:"notifyURL"`
	NotifyText           string `json:"notifyText"`
}

type TailscaleCredential struct {
	ClientID string `json:"clientId"`
	// Omit to retain the saved secret when the client ID is unchanged.
	ClientSecret *string `json:"clientSecret,omitempty"`
}

type TailscaleDNSRecord struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type TailscalePeer struct {
	ID                  string         `json:"id"`
	NodeID              int            `json:"nodeID"`
	PublicKey           string         `json:"publicKey"`
	HostName            string         `json:"hostName"`
	DNSName             string         `json:"dnsName"`
	Os                  string         `json:"os"`
	UserID              int            `json:"userID"`
	TailscaleIPs        []string       `json:"tailscaleIPs"`
	AllowedIPs          []string       `json:"allowedIPs"`
	Tags                []string       `json:"tags"`
	Addrs               []string       `json:"addrs,omitempty"`
	CurAddr             string         `json:"curAddr"`
	Relay               string         `json:"relay"`
	PeerRelay           string         `json:"peerRelay"`
	RxBytes             int            `json:"rxBytes"`
	TxBytes             int            `json:"txBytes"`
	Created             time.Time      `json:"created"`
	LastWrite           *time.Time     `json:"lastWrite,omitempty"`
	LastSeen            *time.Time     `json:"lastSeen,omitempty"`
	LastHandshake       *time.Time     `json:"lastHandshake,omitempty"`
	Online              bool           `json:"online"`
	ExitNode            bool           `json:"exitNode"`
	ExitNodeOption      bool           `json:"exitNodeOption"`
	Active              bool           `json:"active"`
	PeerAPIURL          []string       `json:"peerAPIURL"`
	TaildropTarget      int32          `json:"taildropTarget"`
	NoFileSharingReason string         `json:"noFileSharingReason"`
	CapMap              map[string]any `json:"capMap,omitempty"`
	InNetworkMap        bool           `json:"inNetworkMap"`
	InMagicSock         bool           `json:"inMagicSock"`
	InEngine            bool           `json:"inEngine"`
	KeyExpiry           *time.Time     `json:"keyExpiry,omitempty"`
}

type TailscaleStatus struct {
	Version        string                  `json:"version"`
	Tun            bool                    `json:"tun"`
	BackendState   string                  `json:"backendState"`
	HaveNodeKey    bool                    `json:"haveNodeKey"`
	AuthURL        string                  `json:"authURL"`
	TailscaleIPs   []string                `json:"tailscaleIPs"`
	Health         []string                `json:"health"`
	MagicDNSSuffix string                  `json:"magicDnsSuffix"`
	CurrentTailnet *Tailnet                `json:"currentTailnet,omitempty"`
	CertDomains    []string                `json:"certDomains,omitempty"`
	ExtraRecords   []*TailscaleDNSRecord   `json:"extraRecords,omitempty"`
	ClientVersion  *TailscaleClientVersion `json:"clientVersion,omitempty"`
	Self           *TailscalePeer          `json:"self,omitempty"`
	Peers          []*TailscalePeer        `json:"peers"`
}

type TailscaleUser struct {
	ID            int    `json:"id"`
	LoginName     string `json:"loginName"`
	DisplayName   string `json:"displayName"`
	ProfilePicURL string `json:"profilePicURL"`
}

type User struct {
	ID         int       `json:"id"`
	Username   string    `json:"username"`
	Role       string    `json:"role"`
	CreateTime time.Time `json:"createTime"`
	UpdateTime time.Time `json:"updateTime"`
}
