package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/pancpp/nanotail-portal/app/graph/model"
)

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, passwords model.ChangePassword) (bool, error) {
	return r.changePassword(ctx, passwords)
}

// SetTailscaleCredential is the resolver for the setTailscaleCredential field.
func (r *mutationResolver) SetTailscaleCredential(ctx context.Context, credential model.TailscaleCredential) (bool, error) {
	return r.setTailscaleCredential(ctx, credential)
}

// ClearTailscaleCredential is the resolver for the clearTailscaleCredential field.
func (r *mutationResolver) ClearTailscaleCredential(ctx context.Context) (bool, error) {
	return r.clearTailscaleCredential(ctx)
}

// SetDeviceIP is the resolver for the setDeviceIP field.
func (r *mutationResolver) SetDeviceIP(ctx context.Context, deviceIP *model.DeviceIP) (bool, error) {
	return r.setDeviceIP(ctx, deviceIP)
}

// SetExitNode is the resolver for the setExitNode field.
func (r *mutationResolver) SetExitNode(ctx context.Context, input model.ExitNodeInput) (bool, error) {
	return r.setExitNode(ctx, input)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	return r.user(ctx)
}

// TailscaleClient is the resolver for the tailscaleClient field.
func (r *queryResolver) TailscaleClient(ctx context.Context) (*model.TailscaleClient, error) {
	return r.tailscaleClient(ctx)
}

// TailscaleStatus is the resolver for the tailscaleStatus field.
func (r *queryResolver) TailscaleStatus(ctx context.Context) (*model.TailscaleStatus, error) {
	return r.tailscaleStatus(ctx)
}

// DeviceStatus is the resolver for the deviceStatus field.
func (r *queryResolver) DeviceStatus(ctx context.Context) (*model.DeviceStatus, error) {
	return r.deviceStatus(ctx)
}

// NetworkActivity is the resolver for the networkActivity field.
func (r *queryResolver) NetworkActivity(ctx context.Context) (*model.NetworkActivity, error) {
	return r.networkActivity(ctx)
}

// NetworkActivityHistory is the resolver for the networkActivityHistory field.
func (r *queryResolver) NetworkActivityHistory(ctx context.Context) (*model.NetworkActivityHistory, error) {
	return r.networkActivityHistory(ctx)
}

// TailscaleRouting is the resolver for the tailscaleRouting field.
func (r *queryResolver) TailscaleRouting(ctx context.Context) (*model.TailscaleRouting, error) {
	return r.tailscaleRouting(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
