package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/pancpp/nanotail-portal/app/graph/model"
	"github.com/pancpp/nanotail-portal/conf"
)

// SetPeerRelay is the resolver for the setPeerRelay field.
func (r *mutationResolver) SetPeerRelay(ctx context.Context, input model.PeerRelayInput) (bool, error) {
	return r.setPeerRelay(ctx, input)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, passwords model.ChangePassword) (bool, error) {
	return r.changePassword(ctx, passwords)
}

// SetTailscaleCredential is the resolver for the setTailscaleCredential field.
func (r *mutationResolver) SetTailscaleCredential(ctx context.Context, credential model.TailscaleCredential) (bool, error) {
	return r.setTailscaleCredential(ctx, credential)
}

// ClearTailscaleCredential is the resolver for the clearTailscaleCredential field.
func (r *mutationResolver) ClearTailscaleCredential(ctx context.Context) (bool, error) {
	return r.clearTailscaleCredential(ctx)
}

// SetDeviceIP is the resolver for the setDeviceIP field.
func (r *mutationResolver) SetDeviceIP(ctx context.Context, deviceIP *model.DeviceIP) (bool, error) {
	return r.setDeviceIP(ctx, deviceIP)
}

// SetDeviceHostname is the resolver for the setDeviceHostname field.
func (r *mutationResolver) SetDeviceHostname(ctx context.Context, hostname string) (bool, error) {
	return r.setDeviceHostname(ctx, hostname)
}

// SetRouting is the resolver for the setRouting field.
func (r *mutationResolver) SetRouting(ctx context.Context, input model.RoutingInput) (bool, error) {
	return r.setRouting(ctx, input)
}

// SetTailscaleEnabled is the resolver for the setTailscaleEnabled field.
func (r *mutationResolver) SetTailscaleEnabled(ctx context.Context, enabled bool) (bool, error) {
	return r.setTailscaleEnabled(ctx, enabled)
}

// LogoutTailscale is the resolver for the logoutTailscale field.
func (r *mutationResolver) LogoutTailscale(ctx context.Context) (bool, error) {
	return r.logoutTailscale(ctx)
}

// RenewTailscaleNodeKey is the resolver for the renewTailscaleNodeKey field.
func (r *mutationResolver) RenewTailscaleNodeKey(ctx context.Context) (*model.TailscaleKeyRenewal, error) {
	return r.renewTailscaleNodeKey(ctx)
}

// BeginTailscaleNodeKeyRenewal is the resolver for the beginTailscaleNodeKeyRenewal field.
func (r *mutationResolver) BeginTailscaleNodeKeyRenewal(ctx context.Context, attemptID string) (*model.TailscaleKeyRenewal, error) {
	return r.beginTailscaleNodeKeyRenewal(ctx, attemptID)
}

// CancelTailscaleNodeKeyRenewal is the resolver for the cancelTailscaleNodeKeyRenewal field.
func (r *mutationResolver) CancelTailscaleNodeKeyRenewal(ctx context.Context, attemptID string) (*model.TailscaleKeyRenewal, error) {
	return r.cancelTailscaleNodeKeyRenewal(ctx, attemptID)
}

// PortalVersion is the resolver for the portalVersion field.
func (r *queryResolver) PortalVersion(ctx context.Context) (string, error) {
	version, _, _, _ := conf.GetVersion()
	return version, nil
}

// DeviceID is the resolver for the deviceID field.
func (r *queryResolver) DeviceID(ctx context.Context) (*string, error) {
	return r.deviceID(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	return r.user(ctx)
}

// TailscaleClient is the resolver for the tailscaleClient field.
func (r *queryResolver) TailscaleClient(ctx context.Context) (*model.TailscaleClient, error) {
	return r.tailscaleClient(ctx)
}

// TailscaleStatus is the resolver for the tailscaleStatus field.
func (r *queryResolver) TailscaleStatus(ctx context.Context) (*model.TailscaleStatus, error) {
	return r.tailscaleStatus(ctx)
}

// DeviceStatus is the resolver for the deviceStatus field.
func (r *queryResolver) DeviceStatus(ctx context.Context) (*model.DeviceStatus, error) {
	return r.deviceStatus(ctx)
}

// NetworkActivity is the resolver for the networkActivity field.
func (r *queryResolver) NetworkActivity(ctx context.Context) (*model.NetworkActivity, error) {
	return r.networkActivity(ctx)
}

// NetworkActivityHistory is the resolver for the networkActivityHistory field.
func (r *queryResolver) NetworkActivityHistory(ctx context.Context) (*model.NetworkActivityHistory, error) {
	return r.networkActivityHistory(ctx)
}

// TailscaleRouting is the resolver for the tailscaleRouting field.
func (r *queryResolver) TailscaleRouting(ctx context.Context) (*model.TailscaleRouting, error) {
	return r.tailscaleRouting(ctx)
}

// TailscaleConnection is the resolver for the tailscaleConnection field.
func (r *queryResolver) TailscaleConnection(ctx context.Context) (*model.TailscaleConnection, error) {
	return r.tailscaleConnection(ctx)
}

// TailscaleKeyRenewal is the resolver for the tailscaleKeyRenewal field.
func (r *queryResolver) TailscaleKeyRenewal(ctx context.Context) (*model.TailscaleKeyRenewal, error) {
	return r.tailscaleKeyRenewal(ctx)
}

// LatencyMs is the resolver for the latencyMs field.
func (r *tailscalePeerResolver) LatencyMs(ctx context.Context, obj *model.TailscalePeer) (*float64, error) {
	return r.peerLatency(ctx, obj)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// TailscalePeer returns TailscalePeerResolver implementation.
func (r *Resolver) TailscalePeer() TailscalePeerResolver { return &tailscalePeerResolver{r} }

type (
	mutationResolver      struct{ *Resolver }
	queryResolver         struct{ *Resolver }
	tailscalePeerResolver struct{ *Resolver }
)
